name: Build PDF for release

on:
  release:
    types: [published]

permissions:
  contents: write


jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: text.tex

      # Upload PDF to the GitHub Release
      - name: Upload PDF to release
        uses: softprops/action-gh-release@v2
        with:
          files: text.pdf

